name: campers_closet
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.2
  smooth_page_indicator: ^2.0.1
  exui: ^1.0.11
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
